### ISSUE TITLE
unicode support

### ISSUE THREAD

**Issue by Offirmo** [akZhy/typebot#3]
This lib is awesome !

However, when typeboting unicode chars, they are destroyed.

Could it be fixed ?

**Comment by akzhy** [comment]
Sorry but currently it does not support Unicode typing, but i will do something about it

**Comment by akzhy** [comment]
You can use [this little hack](https://jsfiddle.net/p8p7pqrh/1/) to do it. It is made by adding the unicodes to a dummy element and then the content of that element is given as the argument in the function
