### ISSUE TITLE
blinker customization

### ISSUE THREAD

**Issue by Offirmo** [akZhy/typebot#4]
I'd like to customize the blinker to look like Ubuntu console.

Could this be added ?

**Comment by akzhy** [comment]
Hi, sorry for the delay in response. Check [this](https://jsfiddle.net/p8p7pqrh/) it uses css to style the blinker .

**Comment by akZhy** [comment]
You can use [this little hack](https://jsfiddle.net/p8p7pqrh/1/) to do it. It is made by adding the unicodes to a dummy element and then the content of that element is given as the argument in the function
